import { Inter } from "next/font/google";
import "./globals.css";


import Footer from "./component/footer/footer";
import NewPage from "./component/NewPage/newpage";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div >
          <NewPage/>
        </div>
        {children}
        <div>
          <Footer/>
        </div>
          
      
        
        </body>
    </html>
  );
}
